name: CI reusable
defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  workflow_call:
    inputs:
      lib:
        description: "Library folder name (relative to repo root)"
        required: true
        type: string

jobs:
  to-lowercase:
    runs-on: ubuntu-latest
    outputs:
      repo_lowercase: ${{ steps.lowercase.outputs.repository }}
    steps:
      - id: lowercase
        run: |
          echo "repository=ghcr.io/${GITHUB_REPOSITORY,,}:jazzy" >> $GITHUB_OUTPUT
  test:
    needs: to-lowercase
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.to-lowercase.outputs.repo_lowercase }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: cognitive_robot_abstract_machine
          submodules: recursive

      - name: Initialize submodules explicitly
        run: |
          cd cognitive_robot_abstract_machine
          git config --global --add safe.directory "*"
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install dependencies
        run: |
          cd cognitive_robot_abstract_machine
          source /opt/ros/cram-env/bin/activate
          poetry install

      - name: Build ORM
        if: ${{inputs.lib == 'pycram' || inputs.lib == 'semantic_digital_twin'}}
        run: |
          cd cognitive_robot_abstract_machine/${{ inputs.lib }}/scripts/
          source /opt/ros/overlay_ws/install/setup.bash
          source /opt/ros/cram-env/bin/activate
          python generate_orm.py

      - name: Run tests
        run: |
          source /opt/ros/overlay_ws/install/setup.bash
          source /opt/ros/cram-env/bin/activate
          python -m pytest -sv cognitive_robot_abstract_machine/test/${{ inputs.lib }}_test