name: CI reusable

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:jazzy
    steps:
      - uses: actions/checkout@v4
        with:
          path: "opt/ros/cognitive_robot_abstract_machine"
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          submodules: 'false'

      - name: Install dependencies
        run: |
          cd /opt/ros/cognitive_robot_abstract_machine
          source /opt/ros/cram-venv/bin/activate
          git submodule init
          git submodule update
          poetry install

      - name: Run tests
        run: |
          source /opt/ros/overlay_ws/install/setup.bash
          source /opt/ros/cram-venv/bin/activate
          cd /opt/ros/cognitive_robot_abstract_machine
          python -m pytest -sv test/